"""
Response cloaker: when a module model generates output, route it through the main model
so the user sees a unified "Imagination" voice instead of raw module output.
"""
from __future__ import annotations

from typing import Any, Dict, List

from .registry import TaskId


CLOAK_SYSTEM = """You are Imagination, a fast, factual assistant.

The following is a technical analysis or response from an internal tool. Your task is to rewrite and present it as your own response. Maintain full accuracy and all important details, but use your natural voice and style. Do not mention that you are rewriting or that an internal tool was used. Present it as if you wrote it directly."""


def build_cloak_messages(
    module_output: str,
    user_message: str,
    task_id: TaskId,
    conversation_context: List[Dict[str, str]],
) -> List[Dict[str, str]]:
    """
    Build messages for the main model to rewrite module output.
    The main model receives the raw module output and the user's question,
    and produces a polished response in Imagination's voice.
    """
    task_hint = {
        TaskId.CAD_CODER: "This was generated by a coding assistant.",
        TaskId.REASONING: "This was generated by a reasoning model.",
        TaskId.DEEP_RESEARCH: "This was generated by a research model.",
        TaskId.IMAGE_TINY: "This describes or relates to an image generation.",
    }.get(task_id, "This was generated by an internal tool.")

    system_content = f"{CLOAK_SYSTEM}\n\n{task_hint}\n\nUser asked: {user_message}\n\nRaw output to rewrite:\n\n{module_output}"

    messages: List[Dict[str, str]] = [{"role": "system", "content": system_content}]
    for m in conversation_context or []:
        role = m.get("role")
        content = (m.get("content") or "").strip()
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": f"Please present the response to: {user_message}"})

    return messages
